//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Austin.CleanerUnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Austin.CleanerUnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.0-preview2-003121
        ///1.0.0-preview2-003131
        ///1.0.0-preview2-003148
        ///1.0.0-preview2-003156
        ///1.0.0-preview2.1-003177
        ///1.0.1
        ///1.0.4
        ///1.1.4
        ///1.1.5
        ///1.1.7
        ///1.1.8
        ///1.1.9
        ///1.1.10
        ///1.1.11
        ///1.1.12
        ///1.1.13
        ///2.0.0-preview1-005977
        ///2.0.0-preview2-006497
        ///2.0.0
        ///2.0.3
        ///2.1.0-preview1
        ///2.1.0-preview2
        ///2.1.0-rc1
        ///2.1.2
        ///2.1.4
        ///2.1.101
        ///2.1.105
        ///2.1.200
        ///2.1.202
        ///2.1.300
        ///2.1.301
        ///2.1.302
        ///2.1.400
        ///2.1.401
        ///2.1.402
        ///2.1.403
        ///2.1.500
        ///2.1.504
        ///2.1.505
        ///2.2.100-preview1-009349
        ///2.2.100-preview2-009404
        ///2.2.100-preview3-0094 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EveryDotNetSdkVersion {
            get {
                return ResourceManager.GetString("EveryDotNetSdkVersion", resourceCulture);
            }
        }
    }
}
